class BANK_CODE:
    def __init__(self):
        self.VIETCOMBANK = {"fullname": "Ngân hàng TMCP Ngoại Thương Việt Nam", "bankcode": "970436", "sub_name": "NGÂN HÀNG TMCP NGOẠI THƯƠNG VIỆT NAM"}
        self.BIDV = {"fullname": "Ngân hàng Đầu tư và phát triển Việt Nam", "bankcode": "970418", "sub_name": "NGÂN HÀNG ĐẦU TƯ VÀ PHÁT TRIỂN VIỆT NAM"}
        self.VIETINBANK = {"fullname": "Ngân hàng Công Thương Việt Nam", "bankcode": "970415", "sub_name": "NGÂN HÀNG CÔNG THƯƠNG VIỆT NAM"}
        self.AGRIBANK = {"fullname": "Ngân hàng Nông nghiệp và phát triển nông thôn Việt Nam", "bankcode": "970405", "sub_name": "NGÂN HÀNG NÔNG NGHIỆP VÀ PHÁT TRIỂN NÔNG THÔN VIỆT NAM"}
        self.ABBANK = {"fullname": "Ngân hàng An Bình", "bankcode": "970425", "sub_name": "NGÂN HÀNG AN BÌNH"}
        self.ACB = {"fullname": "Ngân hàng Á Châu", "bankcode": "970416", "sub_name": "NGÂN HÀNG Á CHÂU"}
        self.ANZ = {"fullname": "Ngân hàng TNHH Một Thành Viên ANZ Việt Nam", "bankcode": "01602002", "sub_name": "NGÂN HÀNG TNHH MỘT THÀNH VIÊN ANZ VIỆT NAM"}
        self.BAC_A_BANK = {"fullname": "Ngân hàng Bắc Á", "bankcode": "970409", "sub_name": "NGÂN HÀNG BẮC Á"}
        self.BANGKOK_BANK_TPHCM = {"fullname": "Ngân hàng Bangkok Bank - CN TP Hồ Chí Minh", "bankcode": "79612001", "sub_name": "NGÂN HÀNG BANGKOK BANK - CN TP HỒ CHÍ MINH"}
        self.BANGKOK_BANK_HN = {"fullname": "Ngân hàng Bangkok Bank - CN Hà Nội", "bankcode": "01667001", "sub_name": "NGÂN HÀNG BANGKOK BANK - CN HÀ NỘI"}
        self.BAO_VIET_BANK = {"fullname": "Ngân hàng Bảo Việt", "bankcode": "970438", "sub_name": "NGÂN HÀNG BẢO VIỆT"}
        self.BFCE = {"fullname": "Ngân hàng BPCE IOM", "bankcode": "79601001", "sub_name": "NGÂN HÀNG BPCE IOM"}
        self.BIDC_TPHCM = {"fullname": "Ðầu Tư và Phát Triển Campuchia - CN TP Hồ Chí Minh", "bankcode": "79648001", "sub_name": "ÐẦU TƯ VÀ PHÁT TRIỂN CAMPUCHIA - CN TP HỒ CHÍ MINH"}
        self.BIDC_HN = {"fullname": "Ðầu Tư và Phát Triển Campuchia - CN Hà Nội", "bankcode": "555666", "sub_name": "ÐẦU TƯ VÀ PHÁT TRIỂN CAMPUCHIA - CN HÀ NỘI"}
        self.BNK = {"fullname": "Ngân hàng Busan", "bankcode": "79660001", "sub_name": "NGÂN HÀNG BUSAN"}
        self.BNP_PARIBAS_HCM_TPHCM = {"fullname": "Ngân hàng BNP Paribas – CN TP Hồ Chí Minh", "bankcode": "963666", "sub_name": "NGÂN HÀNG BNP PARIBAS – CN TP HỒ CHÍ MINH"}
        self.BNP_PARIBAS_HN_HN = {"fullname": "Ngân hàng BNP Paribas – CN Hà Nội", "bankcode": "963668", "sub_name": "NGÂN HÀNG BNP PARIBAS – CN HÀ NỘI"}
        self.BOCHK_TPHCM = {"fullname": "Ngân hàng Bank of China (Hongkong) Limited – CN TP Hồ Chí Minh", "bankcode": "963688", "sub_name": "NGÂN HÀNG BANK OF CHINA (HONGKONG) LIMITED – CN TP HỒ CHÍ MINH"}
        self.BOCOM = {"fullname": "Ngân hàng Bank of Communications Co., Ltd", "bankcode": "79615001", "sub_name": "NGÂN HÀNG BANK OF COMMUNICATIONS CO., LTD"}
        self.BOI_BANK_OF_INDIA = {"fullname": "Ngân hàng Bank of India", "bankcode": "79659001", "sub_name": "NGÂN HÀNG BANK OF INDIA"}
        self.BSP = {"fullname": "Ngân hàng SINOPAC", "bankcode": "79632001", "sub_name": "NGÂN HÀNG SINOPAC"}
        self.BVBANK_TIMO = {"fullname": "Ngân hàng số Timo - Ngân hàng TMCP Bản Việt", "bankcode": "963388", "sub_name": "NGÂN HÀNG SỐ TIMO - NGÂN HÀNG TMCP BẢN VIỆT"}
        self.CAKE = {"fullname": "Ngân hàng CAKE BY VPBANK", "bankcode": "546034", "sub_name": "NGÂN HÀNG CAKE BY VPBANK"}
        self.VCBNEO = {"fullname": "Ngân hàng TM TNHH Một Thành Viên Ngoại thương Công nghệ số", "bankcode": "970444", "sub_name": "NGÂN HÀNG TM TNHH MỘT THÀNH VIÊN NGOẠI THƯƠNG CÔNG NGHỆ SỐ"}
        self.CCB = {"fullname": "Ngân hàng Xây dựng Trung Quốc", "bankcode": "79611001", "sub_name": "NGÂN HÀNG XÂY DỰNG TRUNG QUỐC"}
        self.CIMB = {"fullname": "Ngân hàng TNHH MTV CIMB Việt\xa0Nam", "bankcode": "422589", "sub_name": "NGÂN HÀNG TNHH MTV CIMB VIỆT\xa0NAM"}
        self.CITIBANK_HN = {"fullname": "Ngân hàng Citibank Việt Nam - CN Hà Nội", "bankcode": "01605001", "sub_name": "NGÂN HÀNG CITIBANK VIỆT NAM - CN HÀ NỘI"}
        self.CITIBANK = {"fullname": "Ngân hàng Citibank Việt Nam", "bankcode": "533948", "sub_name": "NGÂN HÀNG CITIBANK VIỆT NAM"}
        self.CO_OPBANK = {"fullname": "Ngân hàng Hợp tác xã Việt Nam", "bankcode": "970446", "sub_name": "NGÂN HÀNG HỢP TÁC XÃ VIỆT NAM"}
        self.CREDIT_AGRICOLE = {"fullname": "Ngân hàng Crédit Agricole Corporate and Investment - CN TP Hồ Chí Minh", "bankcode": "79621001", "sub_name": "NGÂN HÀNG CRÉDIT AGRICOLE CORPORATE AND INVESTMENT - CN TP HỒ CHÍ MINH"}
        self.CTBC = {"fullname": "Ngân hàng TNHH CTBC", "bankcode": "79629001", "sub_name": "NGÂN HÀNG TNHH CTBC"}
        self.CUB_CL = {"fullname": "Ngân hàng Cathay United - CN Chu Lai", "bankcode": "49634001", "sub_name": "NGÂN HÀNG CATHAY UNITED - CN CHU LAI"}
        self.CUB_HCM_TPHCM = {"fullname": "Cathay United Bank – CN TP Hồ Chí Minh", "bankcode": "168999", "sub_name": "CATHAY UNITED BANK – CN TP HỒ CHÍ MINH"}
        self.DBS = {"fullname": "Ngân hàng DBS - CN Hồ Chí Minh", "bankcode": "796500", "sub_name": "NGÂN HÀNG DBS - CN HỒ CHÍ MINH"}
        self.DEUTSCHE_BANK = {"fullname": "Ngân hàng DEUTSCHE BANK", "bankcode": "79619001", "sub_name": "NGÂN HÀNG DEUTSCHE BANK"}
        self.DGB_DAEGU_CN_HCM_TPHCM = {"fullname": "Ngân hàng Daegu - CN TP Hồ Chí Minh", "bankcode": "79668001", "sub_name": "NGÂN HÀNG DAEGU - CN TP HỒ CHÍ MINH"}
        self.VIKKI_BANK = {"fullname": "Ngân hàng Trách nhiệm hữu hạn Một thành viên số Vikki", "bankcode": "970406", "sub_name": "NGÂN HÀNG TRÁCH NHIỆM HỮU HẠN MỘT THÀNH VIÊN SỐ VIKKI"}
        self.ESB = {"fullname": "Ngân hàng E.SUN BANK", "bankcode": "75658001", "sub_name": "NGÂN HÀNG E.SUN BANK"}
        self.EXIMBANK = {"fullname": "Ngân hàng Xuất Nhập khẩu", "bankcode": "970431", "sub_name": "NGÂN HÀNG XUẤT NHẬP KHẨU"}
        self.FIRSTBANK_HN = {"fullname": "Ngân hàng First Commercial Bank - CN Hà Nội", "bankcode": "01608001", "sub_name": "NGÂN HÀNG FIRST COMMERCIAL BANK - CN HÀ NỘI"}
        self.FIRSTBANK_TPHCM = {"fullname": "Ngân hàng First Commercial Bank - CN TP Hồ Chí Minh", "bankcode": "79630001", "sub_name": "NGÂN HÀNG FIRST COMMERCIAL BANK - CN TP HỒ CHÍ MINH"}
        self.GPBANK = {"fullname": "Ngân hàng Dầu khí toàn cầu", "bankcode": "970408", "sub_name": "NGÂN HÀNG DẦU KHÍ TOÀN CẦU"}
        self.HANOI_ABC_HN = {"fullname": "Ngân hàng Agricultural Bank of China Limited - CN Hà Nội", "bankcode": "01664001", "sub_name": "NGÂN HÀNG AGRICULTURAL BANK OF CHINA LIMITED - CN HÀ NỘI"}
        self.HD_BANK = {"fullname": "Ngân hàng Phát triển TP.HCM", "bankcode": "970437", "sub_name": "NGÂN HÀNG PHÁT TRIỂN TP.HCM"}
        self.HLBVN = {"fullname": "Ngân hàng HongLeong Việt Nam", "bankcode": "970442", "sub_name": "NGÂN HÀNG HONGLEONG VIỆT NAM"}
        self.HSBC = {"fullname": "Ngân hàng TNHH MTV HSBC Việt Nam", "bankcode": "458761", "sub_name": "NGÂN HÀNG TNHH MTV HSBC VIỆT NAM"}
        self.HUA_NAN_TPHCM = {"fullname": "Ngân hàng Hua Nam Commercial Bank, Ltd  - CN TP Hồ Chí Minh", "bankcode": "79640001", "sub_name": "NGÂN HÀNG HUA NAM COMMERCIAL BANK, LTD  - CN TP HỒ CHÍ MINH"}
        self.IBK_BANK_HN_HN = {"fullname": "Ngân hàng Công nghiệp Hàn Quốc  - CN Hà Nội", "bankcode": "970455", "sub_name": "NGÂN HÀNG CÔNG NGHIỆP HÀN QUỐC  - CN HÀ NỘI"}
        self.IBK_HCM_TPHCM = {"fullname": "Ngân hàng Công nghiệp Hàn Quốc - CN TP Hồ Chí Minh", "bankcode": "970456", "sub_name": "NGÂN HÀNG CÔNG NGHIỆP HÀN QUỐC - CN TP HỒ CHÍ MINH"}
        self.ICBC = {"fullname": "Ngân hàng Công Thương Trung Quốc", "bankcode": "01649001", "sub_name": "NGÂN HÀNG CÔNG THƯƠNG TRUNG QUỐC"}
        self.IVB = {"fullname": "\xa0Ngân hàng TNHH Indovina", "bankcode": "970434", "sub_name": "\xa0NGÂN HÀNG TNHH INDOVINA"}
        self.J_P_MORGAN = {"fullname": "Ngân hàng JPMorgan Chase, N.A.", "bankcode": "79627001", "sub_name": "NGÂN HÀNG JPMORGAN CHASE, N.A."}
        self.KB_HCM_TPHCM = {"fullname": "Ngân hàng Ngân hàng Kookmin - CN TP Hồ Chí Minh", "bankcode": "970463", "sub_name": "NGÂN HÀNG NGÂN HÀNG KOOKMIN - CN TP HỒ CHÍ MINH"}
        self.KB_HN_HN = {"fullname": "Ngân hàng Kookmin - CN Hà Nội", "bankcode": "970462", "sub_name": "NGÂN HÀNG KOOKMIN - CN HÀ NỘI"}
        self.KBANK_TPHCM = {"fullname": "Ngân hàng đại chúng TNHH KASIKORNBANK - CN TP Hồ Chí Minh", "bankcode": "79669001", "sub_name": "NGÂN HÀNG ĐẠI CHÚNG TNHH KASIKORNBANK - CN TP HỒ CHÍ MINH"}
        self.KEB_HANA_HN = {"fullname": "Ngân hàng KEB HANA – CN Hà Nội", "bankcode": "970467", "sub_name": "NGÂN HÀNG KEB HANA – CN HÀ NỘI"}
        self.KEB_HANA_TPHCM = {"fullname": "Ngân hàng KEB HANA  - CN TP Hồ Chí Minh", "bankcode": "79656001", "sub_name": "NGÂN HÀNG KEB HANA  - CN TP HỒ CHÍ MINH"}
        self.KIEN_LONG_BANK = {"fullname": "Ngân hàng Kiên Long", "bankcode": "970452", "sub_name": "NGÂN HÀNG KIÊN LONG"}
        self.LPBANK = {"fullname": "Ngân hàng TMCP Lộc Phát Việt Nam", "bankcode": "970449", "sub_name": "NGÂN HÀNG TMCP LỘC PHÁT VIỆT NAM"}
        self.LIOBANK = {"fullname": "Ngân hàng số Liobank – Ngân hàng TMCP Phương Đông", "bankcode": "963369", "sub_name": "NGÂN HÀNG SỐ LIOBANK – NGÂN HÀNG TMCP PHƯƠNG ĐÔNG"}
        self.MAFC = {"fullname": "Công ty Tài chính TNHH MTV Mirae Asset Việt Nam", "bankcode": "977777", "sub_name": "CÔNG TY TÀI CHÍNH TNHH MTV MIRAE ASSET VIỆT NAM"}
        self.MB = {"fullname": "Ngân hàng Quân Đội", "bankcode": "970422", "sub_name": "NGÂN HÀNG QUÂN ĐỘI"}
        self.MAYBANK_HANOI_HN = {"fullname": "Ngân hàng Malayan Banking Berhad - CN Hà Nội", "bankcode": "01609001", "sub_name": "NGÂN HÀNG MALAYAN BANKING BERHAD - CN HÀ NỘI"}
        self.MAYBANK_HCMC = {"fullname": "Ngân hàng Malayan Banking Berhad TP. Hồ Chí Minh", "bankcode": "79635001", "sub_name": "NGÂN HÀNG MALAYAN BANKING BERHAD TP. HỒ CHÍ MINH"}
        self.MEGA_ICBC_TPHCM = {"fullname": "Ngân hàng Mega International Commercial Bank Co., Ltd  - CN TP Hồ Chí Minh", "bankcode": "79623001", "sub_name": "NGÂN HÀNG MEGA INTERNATIONAL COMMERCIAL BANK CO., LTD  - CN TP HỒ CHÍ MINH"}
        self.MIZUHO_HN = {"fullname": "Ngân hàng Mizuho Bank, LTd - Chi nhánh Hà Nội", "bankcode": "01613001", "sub_name": "NGÂN HÀNG MIZUHO BANK, LTD - CHI NHÁNH HÀ NỘI"}
        self.MIZUHO = {"fullname": "Ngân hàng Mizuho Bank, LTd", "bankcode": "79639001", "sub_name": "NGÂN HÀNG MIZUHO BANK, LTD"}
        self.MSB = {"fullname": "Ngân hàng Hàng Hải", "bankcode": "970426", "sub_name": "NGÂN HÀNG HÀNG HẢI"}
        self.MUFG_TPHCM = {"fullname": "Ngân hàng MUFG Bank. Ltd - CN TP Hồ Chí Minh", "bankcode": "79622001", "sub_name": "NGÂN HÀNG MUFG BANK. LTD - CN TP HỒ CHÍ MINH"}
        self.MUFG_HN = {"fullname": "Ngân hàng MUFG Bank. Ltd – Chi Nhánh Hà Nội", "bankcode": "01653001", "sub_name": "NGÂN HÀNG MUFG BANK. LTD – CHI NHÁNH HÀ NỘI"}
        self.NAM_A_BANK = {"fullname": "Ngân hàng Nam Á", "bankcode": "970428", "sub_name": "NGÂN HÀNG NAM Á"}
        self.NAPAS = {"fullname": "Công ty Cổ phần Thanh toán Quốc gia Việt Nam", "bankcode": "971100", "sub_name": "CÔNG TY CỔ PHẦN THANH TOÁN QUỐC GIA VIỆT NAM"}
        self.NCB = {"fullname": "Ngân hàng Quốc Dân", "bankcode": "970419", "sub_name": "NGÂN HÀNG QUỐC DÂN"}
        self.NONGHUYP_HN = {"fullname": "Ngân hàng Nonghuyp - Chi nhánh Hà Nội", "bankcode": "801011", "sub_name": "NGÂN HÀNG NONGHUYP - CHI NHÁNH HÀ NỘI"}
        self.OCB = {"fullname": "Ngân hàng Phương Đông", "bankcode": "970448", "sub_name": "NGÂN HÀNG PHƯƠNG ĐÔNG"}
        self.OCBC_TPHCM = {"fullname": "Ngân hàng Oversea-Chinese Banking Corporation LTD  - CN TP Hồ Chí Minh", "bankcode": "79625001", "sub_name": "NGÂN HÀNG OVERSEA-CHINESE BANKING CORPORATION LTD  - CN TP HỒ CHÍ MINH"}
        self.MBV = {"fullname": "NH TNHH MTV Việt Nam Hiện Đại", "bankcode": "970414", "sub_name": "NH TNHH MTV VIỆT NAM HIỆN ĐẠI"}
        self.PBVN = {"fullname": "Ngân hàng TNHH MTV Public Viet Nam", "bankcode": "970439", "sub_name": "NGÂN HÀNG TNHH MTV PUBLIC VIET NAM"}
        self.PGBANK = {"fullname": "Ngân hàng TMCP Thịnh vượng và Phát triển (PGBANK)", "bankcode": "970430", "sub_name": "NGÂN HÀNG TMCP THỊNH VƯỢNG VÀ PHÁT TRIỂN (PGBANK)"}
        self.PVCOMBANK = {"fullname": "Ngân hàng Đại chúng", "bankcode": "970412", "sub_name": "NGÂN HÀNG ĐẠI CHÚNG"}
        self.SACOMBANK = {"fullname": "Ngân hàng Sài Gòn thương tín", "bankcode": "970403", "sub_name": "NGÂN HÀNG SÀI GÒN THƯƠNG TÍN"}
        self.SAIGONBANK = {"fullname": "Ngân hàng Sài Gòn Công Thương", "bankcode": "970400", "sub_name": "NGÂN HÀNG SÀI GÒN CÔNG THƯƠNG"}
        self.SCB = {"fullname": "Ngân hàng Sài Gòn", "bankcode": "970429", "sub_name": "NGÂN HÀNG SÀI GÒN"}
        self.SCB_TPHCM = {"fullname": "Ngân hàng The Siam Commercial Bank Public Company Limited  - CN TP Hồ Chí Minh", "bankcode": "79600001", "sub_name": "NGÂN HÀNG THE SIAM COMMERCIAL BANK PUBLIC COMPANY LIMITED  - CN TP HỒ CHÍ MINH"}
        self.SCVN = {"fullname": "Ngân hàng TNHH MTV Standard Chartered Việt Nam", "bankcode": "970410", "sub_name": "NGÂN HÀNG TNHH MTV STANDARD CHARTERED VIỆT NAM"}
        self.SEABANK = {"fullname": "Ngân hàng Đông Nam Á", "bankcode": "970440", "sub_name": "NGÂN HÀNG ĐÔNG NAM Á"}
        self.SHB_HN = {"fullname": "Ngân hàng Sài Gòn Hà Nội", "bankcode": "970443", "sub_name": "NGÂN HÀNG SÀI GÒN HÀ NỘI"}
        self.SHINHAN = {"fullname": "Ngân hàng Shinhan Bank Việt Nam", "bankcode": "970424", "sub_name": "NGÂN HÀNG SHINHAN BANK VIỆT NAM"}
        self.SMBC = {"fullname": "Ngân hàng Sumitomo Mitsui banking corporation", "bankcode": "01636001", "sub_name": "NGÂN HÀNG SUMITOMO MITSUI BANKING CORPORATION"}
        self.SVFC = {"fullname": "Công ty Tài chính TNHH MTV Shinhan Việt Nam", "bankcode": "963368", "sub_name": "CÔNG TY TÀI CHÍNH TNHH MTV SHINHAN VIỆT NAM"}
        self.TAIPEI_FUBON = {"fullname": "Ngân hàng Hua Nam Commercial Bank, Ltd  – Chi nhánh Bình Dương", "bankcode": "74655001", "sub_name": "NGÂN HÀNG HUA NAM COMMERCIAL BANK, LTD  – CHI NHÁNH BÌNH DƯƠNG"}
        self.TAIPEI_FUBON_TPHCM = {"fullname": "Ngân hàng Taipei Fubon Commercial Bank Co., Ltd  - CN TP Hồ Chí Minh", "bankcode": "79651001", "sub_name": "NGÂN HÀNG TAIPEI FUBON COMMERCIAL BANK CO., LTD  - CN TP HỒ CHÍ MINH"}
        self.TAIPEI_FUBONC_B = {"fullname": "Ngân hàng TAIPEI FUBON", "bankcode": "01642001", "sub_name": "NGÂN HÀNG TAIPEI FUBON"}
        self.TECHCOMBANK = {"fullname": "Ngân hàng Kỹ thương Việt Nam", "bankcode": "970407", "sub_name": "NGÂN HÀNG KỸ THƯƠNG VIỆT NAM"}
        self.TPBANK = {"fullname": "Ngân hàng Tiên phong", "bankcode": "970423", "sub_name": "NGÂN HÀNG TIÊN PHONG"}
        self.UBANK = {"fullname": "Ngân hàng UBANK BY VPBANK", "bankcode": "546035", "sub_name": "NGÂN HÀNG UBANK BY VPBANK"}
        self.UMEE = {"fullname": "Ngân hàng số UMEE by Kienlongbank", "bankcode": "963399", "sub_name": "NGÂN HÀNG SỐ UMEE BY KIENLONGBANK"}
        self.UOB_VIETNAM = {"fullname": "Ngân hàng TNHH MTV UOB Việt Nam", "bankcode": "970458", "sub_name": "NGÂN HÀNG TNHH MTV UOB VIỆT NAM"}
        self.VBSP = {"fullname": "Ngân hàng Chính sách Xã hội VBSP", "bankcode": "999888", "sub_name": "NGÂN HÀNG CHÍNH SÁCH XÃ HỘI VBSP"}
        self.VDB = {"fullname": "Ngân hàng Phát triển Việt Nam", "bankcode": "01208001", "sub_name": "NGÂN HÀNG PHÁT TRIỂN VIỆT NAM"}
        self.VIB = {"fullname": "Ngân hàng Quốc tế", "bankcode": "970441", "sub_name": "NGÂN HÀNG QUỐC TẾ"}
        self.VIET_A_BANK = {"fullname": "Ngân hàng Việt Á", "bankcode": "970427", "sub_name": "NGÂN HÀNG VIỆT Á"}
        self.VIET_CAPITAL_BANK = {"fullname": "Ngân hàng Bản Việt", "bankcode": "970454", "sub_name": "NGÂN HÀNG BẢN VIỆT"}
        self.VIETBANK = {"fullname": "Ngân hàng Việt Nam Thương Tín", "bankcode": "970433", "sub_name": "NGÂN HÀNG VIỆT NAM THƯƠNG TÍN"}
        self.VIETTEL_MONEY = {"fullname": "Viettel Money", "bankcode": "971005", "sub_name": "VIETTEL MONEY"}
        self.VINASIAM_BANK = {"fullname": "Ngân hàng liên doanh Việt Thái - Chi nhánh Đồng Nai", "bankcode": "75504001", "sub_name": "NGÂN HÀNG LIÊN DOANH VIỆT THÁI - CHI NHÁNH ĐỒNG NAI"}
        self.VNPT_MONEY = {"fullname": "VNPT Money", "bankcode": "971011", "sub_name": "VNPT MONEY"}
        self.VPBANK = {"fullname": "Ngân hàng Việt Nam Thịnh Vượng", "bankcode": "970432", "sub_name": "NGÂN HÀNG VIỆT NAM THỊNH VƯỢNG"}
        self.WOORI_BANK = {"fullname": "Ngân hàng Woori Việt Nam", "bankcode": "970457", "sub_name": "NGÂN HÀNG WOORI VIỆT NAM"}
        self.WOORI_BANK_VIETNAM_TPHCM = {"fullname": "Ngân hàng TNHH MTV Woori Việt Nam - CN TP Hồ Chí Minh", "bankcode": "79637001", "sub_name": "NGÂN HÀNG TNHH MTV WOORI VIỆT NAM - CN TP HỒ CHÍ MINH"}
        self.SCSB = {"fullname": "Ngân hàng The Shanghai Commercial & Savings Bank. Ltđ – CN Đồng Nai", "bankcode": "75606001", "sub_name": "NGÂN HÀNG THE SHANGHAI COMMERCIAL & SAVINGS BANK. LTĐ – CN ĐỒNG NAI"}
        self.VIKKI_BY_HDBANK = {"fullname": "Kênh số hóa Vikki  – trực thuộc HDBank", "bankcode": "963311", "sub_name": "KÊNH SỐ HÓA VIKKI  – TRỰC THUỘC HDBANK"}
        self.PVCOMBANK_PAY = {"fullname": "Ngân hàng số PVcombank", "bankcode": "971133", "sub_name": "NGÂN HÀNG SỐ PVCOMBANK"}

